In [1]:
import numpy as np

In [3]:
list1 = np.array([1,2,3])
print(list1)

[1 2 3]


In [5]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c = np.array([1,2,3], dtype = float)
print(c)

[1. 2. 3.]


In [ ]:
d = np.arange(1,11,2) # same as range
print(d)

[1 3 5 7 9]


In [ ]:
e = np.arange(1,11).reshape(5,2)
print(e)
# reshape will convert the given array into (rows, columns) dimension


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
f = np.ones((3,4), dtype = int)
print(f)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
g = np.zeros((2,2), dtype=int)
print(g)

[[0 0]
 [0 0]]


In [18]:
h = np.random.random((3,4))
print(h)

i = np.linspace(1,10,3, dtype=int)
print(i)

[[0.07060942 0.27426944 0.70193408 0.8367179 ]
 [0.53045245 0.01605347 0.46981849 0.32806142]
 [0.17663897 0.2227236  0.22700265 0.24235072]]
[ 1  5 10]


In [19]:
print(np.identity(4, dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [21]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# num of dims
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape: num of rows and cols
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size : no of elemnets
print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [ ]:
# itemsize: returns the size of one element in bytes
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [29]:
# dtype : returns the datatupe of one element
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [32]:
# astype : return a new numpy object of the new dtype
a3 = a3.astype(np.int32)
print(a3.dtype)

int32


In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
print(2 * a1)
# here, you can do scalar +,-,*,/,**,% numpy array and it will conduct the operation on each element

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [35]:
print(a1 > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [ ]:
print(a1 + a2)
# here, you can do numpy array +,-,*,/,**,% numpy array and it will conduct the operation element on element

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
print(a1)
print(np.min(a1))
print(np.min(a1, axis = 0)) # this returns the smallest element in each column
print(np.min(a1, axis = 1)) # this returns the smallest element in each row

# you can do the same for min/max/sum/prod/mean/median/var/std

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
[0 1 2 3]
[0 4 8]


In [ ]:
# dot product (matrix multiplication)
a1 = np.random.random((3,4)) * 100
a2 = np.random.random((4,3)) * 100
print(np.dot(a1, a2))

[[ 5444.34121668 14282.00703527 13309.74059156]
 [ 2288.72009076 13085.31866896 10168.53187945]
 [ 3560.49958102 15573.80267187 13078.07317684]]
