**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
#Code here
output = np.zeros(10, dtype = int)
output[4] = 1
output

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a = int(input("Enter number 1: "))
b = int(input("Enter number 2: "))
arr = np.random.random((a,b))
print(arr)
print(np.mean(arr))

Enter number 1: 2
Enter number 2: 3
[[0.29142153 0.43556111 0.93669635]
 [0.4220908  0.15028907 0.20607361]]
0.40702207847529454


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [8]:
#Code here
def build_arr(a, b):
  output = np.zeros((a,b), dtype = int)
  output[0] = np.array([1]*b)
  output[a-1] = np.array([1]*b)

  output[:,0] = np.array([1]*a)
  output[:,b-1] = np.array([1]*a)

  return output

print(build_arr(3,4))

[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [12]:
#Code here
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Not possible

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [15]:
#Code here
output = np.tile(np.arange(5), (5,1))
print(output)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [16]:
#code here
def find_dist(points, target):
    dists = np.linalg.norm(points - target, axis=1)
    return dists.astype(int)



###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
#Code here
array= np.random.random((6,7,8))
x = int(99//(7*8))
y = 99%(7*8) // 8
z = 99%(7*8) % 8
print(x,y,z)

1 5 3


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [21]:
#Code here
def rev_numpy(arr):
  output = np.array(arr.split(), dtype= float)
  return output[::-1]



### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [22]:
#Code here
def count_elements(arr):
  return np.size

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [23]:
#Code here
def get_softmax(arr):
  e_x = np.exp(arr)
  return e_x / np.sum(e_x)

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [24]:
#Coder here
def vertical_stack(*a):
  output = a[0]
  for i in range(1, len(a)):
    if not isinstance(a[i], np.ndarray):
      raise TypeError("Only np arrays")
    output = np.vstack((output, a[i]))
  return output

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [28]:
import datetime as dt

def date_array(start, end):
    format = "%Y-%m-%d"
    start = dt.datetime.strptime(start, format)
    end = dt.datetime.strptime(end, format)

    days = (end - start).days

    return np.array([start + dt.timedelta(days=int(i)) for i in np.arange(days+1)])

print(date_array('2020-11-25', '2020-11-30'))


[datetime.datetime(2020, 11, 25, 0, 0)
 datetime.datetime(2020, 11, 26, 0, 0)
 datetime.datetime(2020, 11, 27, 0, 0)
 datetime.datetime(2020, 11, 28, 0, 0)
 datetime.datetime(2020, 11, 29, 0, 0)
 datetime.datetime(2020, 11, 30, 0, 0)]


###`Q-14:` Subtract the mean of each row from a matrix.

In [32]:

matrix = np.random.random((3,4))
mean = np.mean(matrix, axis=1, keepdims=True)
output = matrix - mean
print(output)

[[-0.13718855 -0.46537689  0.42455333  0.1780121 ]
 [-0.09064181  0.33756484 -0.19634995 -0.05057307]
 [ 0.38109714 -0.14939813 -0.16952849 -0.06217053]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [34]:
#Code here
def swap_cols(arr):
  temp = arr[:, 0].copy()
  arr[:, 0] = arr[:,1]
  arr[:, 1] = temp

arr = np.random.random((3,4))
print(arr)
swap_cols(arr)
print(arr)

[[0.23697838 0.65268367 0.01001672 0.52895415]
 [0.37341807 0.93091128 0.14322434 0.4098003 ]
 [0.05616215 0.28421694 0.60502296 0.74030619]]
[[0.65268367 0.23697838 0.01001672 0.52895415]
 [0.93091128 0.37341807 0.14322434 0.4098003 ]
 [0.28421694 0.05616215 0.60502296 0.74030619]]


###`Q-16:` Replace odd elements in arrays with -1.

In [35]:
#Code here
def replace_elements(arr):
  mask = arr % 2 == 1
  arr[mask] = -1


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [38]:
#Code here
def build_max(a1, a2):
  output = a1.copy()
  mask = a2 > a1
  output[mask] = a2[mask]
  return output

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
print(build_max(a,b))

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [40]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[4278, 6805, 3289, 3262, 4613],
       [3926, 7300, 9635, 9508, 5251],
       [5917, 3630, 2966, 4558, 4700],
       [1770, 6849,  675, 3782, 7528],
       [7066, 2691, 3688, 1373,   82],
       [ 344, 9776, 4293, 7720, 3147],
       [ 353,  876, 2169, 6085, 8821],
       [4967, 4944, 1988, 4843, 5970]])

In [42]:
#Code here
def fetch_alternate_cols(arr):
  return arr[:, ::2]

print(fetch_alternate_cols(arr1))

def normalize(arr):
  min = np.min(arr)
  max = np.max(arr)
  return (arr - min) / (max - min)

print(normalize(arr1))

[[4278 3289 4613]
 [3926 9635 5251]
 [5917 2966 4700]
 [1770  675 7528]
 [7066 3688   82]
 [ 344 4293 3147]
 [ 353 2169 8821]
 [4967 1988 5970]]
[[0.43284506 0.69352177 0.33082319 0.32803796 0.46740252]
 [0.39653394 0.74458428 0.98545492 0.97235403 0.53321642]
 [0.60191871 0.36599959 0.29750361 0.4617289  0.47637714]
 [0.17412833 0.69806066 0.06117186 0.38167939 0.76810398]
 [0.72044564 0.26913555 0.37198267 0.13317516 0.        ]
 [0.02702703 1.         0.43439241 0.78791005 0.31617495]
 [0.02795544 0.08190633 0.21528781 0.61924902 0.90148545]
 [0.50391995 0.50154735 0.19661646 0.49112853 0.60738601]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [43]:
#Code here
def nth_largest(arr, n):
  if n > len(arr):
    print("n is too large")
    return
  return sorted(arr)[n-1]



###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [45]:
#code here
def make_pattern(a):
  a1 = np.repeat(a, 3)
  a2 = np.tile(a, 3)
  output = np.concatenate([a1, a2])
  return output

print(make_pattern(np.array([1,2,3])))



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
