###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
# code hhere
import numpy as np
a = np.random.randint(1,100,12).reshape((3,4))

print(np.sort(a))

print(a[a[:, 1].argsort()])

print(a[np.argsort(a.max(axis=1))])

print(np.sort(a, axis=None).reshape(a.shape))

[[33 57 76 97]
 [21 39 60 82]
 [14 24 43 54]]
[[43 14 54 24]
 [82 21 60 39]
 [76 33 57 97]]
[[43 14 54 24]
 [82 21 60 39]
 [76 33 57 97]]
[[14 21 24 33]
 [39 43 54 57]
 [60 76 82 97]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [2]:
# code here
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = np.array([41, 87, 72, 36, 92])

marks = np.append(marks, extra_subject.reshape(-1,1), axis = 1)

rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

marks = np.append(marks, [rec1, rec2], axis = 0)

marks = np.append(marks, np.sum(marks, axis = 1).reshape(-1,1), axis = 1)

print(marks)

print(marks[marks[:, 5].argsort()][::-1][0:2])

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [3]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.unique(arr, axis=0))
print(np.unique(arr, axis = 1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [4]:

# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.flip(arr))

[[1 1 3 3 2 1]
 [8 8 8 3 2 1]
 [8 8 2 1 9 0]
 [1 1 3 3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [5]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )

X = 6

print(np.where(np.any(arr > X, axis=1))[0])

[1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [6]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [8]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )

print(arr.flatten())

[ 1  2  3  4  5 10 -3 30  4  5  3  2  5 -4  5  9  7  3  6  5]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [12]:
# code here
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(np.max(arr))
print(np.min(arr))
print(arr[(arr != np.max(arr)) &(arr != np.min(arr))])

994
112
[337 175 672 942 961 255 324 977 882 221 724 911 148 766 977 153 541 149
 828 531 803 946 894 323 499 690 508 411 519 178 201 261 209 526 873 956
 550 120 740 552 441 358 527 131 726 823 385 121 490 628 225 478 120 491
 681 630 858 209 449 554 789 348 150 161 678 820 548 776 445 707 420 803
 388 211 935 896 944 967 807 483 195 330 747 831 266 869 774 823 186 501
 606 718 922 669 120 951 432 913 334 357 578 708 780 894 473 796 799 573
 905 311 340 802 968 643 926 287 568 245 138 677 224 411 909 674 137 954
 651 279 190 678 759 910 813 114 140 603 523 705 166 699 563 792 133 620
 900 377 932 177 684 620 365 668 539 340 498 627 302 593 296 302 480 868
 574 386 879 554 132 852 745 635 838 663 927 815 376 711 538 683 151 862
 597 197 688 508 176 796 912 528 257 478 569 411 289 936 946 564 159 990]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code he
??

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [15]:
# code here
arr = np.random.random(100)
arr = np.round(arr, decimals = 3)

print(np.percentile(arr, q = 0))
print(np.percentile(arr, q = 1))
print(np.percentile(arr, q = 0.51) - np.percentile(arr, q = 0.5))


0.001
0.0039700000000000004
2.9699999999999692e-05
